CREATE TYPE "public"."verification_status" AS ENUM('unowned', 'registered', 'transferring');--> statement-breakpoint
CREATE TABLE "productVerifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"serialNumber" varchar(50) NOT NULL,
	"productId" integer,
	"productNameTR" varchar(255),
	"productNameEN" varchar(255),
	"productNameAR" varchar(255),
	"collection" varchar(100),
	"collectionYear" varchar(20),
	"batchNumber" varchar(100),
	"productionDate" varchar(100),
	"material" varchar(255),
	"imageUrl" varchar(500),
	"orderNumber" varchar(50),
	"status" "verification_status" DEFAULT 'unowned' NOT NULL,
	"ownerUserId" integer,
	"ownerName" varchar(255),
	"ownerEmail" varchar(320),
	"registeredAt" timestamp,
	"transferToName" varchar(255),
	"transferToEmail" varchar(320),
	"transferNote" text,
	"transferInitiatedAt" timestamp,
	"scanCount" integer DEFAULT 0 NOT NULL,
	"firstScannedAt" timestamp,
	"lastScannedAt" timestamp,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "productVerifications_serialNumber_unique" UNIQUE("serialNumber")
);
