export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "dev-secret-change-in-production",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  adminPassword: process.env.ADMIN_PASSWORD ?? "",
  corsOrigin: process.env.CORS_ORIGIN ?? "",
  serveStatic: process.env.SERVE_STATIC === "true",
  smtp: {
    host:   process.env.SMTP_HOST   ?? "",
    port:   Number(process.env.SMTP_PORT)   || 587,
    secure: process.env.SMTP_SECURE === "true",
    user:   process.env.SMTP_USER   ?? "",
    pass:   process.env.SMTP_PASS   ?? "",
    from:   process.env.SMTP_FROM   ?? "",
  },
};
